addons:
  apt:
    update: true
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - env: TOXENV=flake8
before_install:
  - sudo apt-get -y install python3-systemd
install:
  - pip install tox
script:
  - tox
